spring.application.name=chatapp
server.port=9090

# MongoDB Atlas Connection (Custom Property to bypass Spring defaults)
app.mongodb.uri=mongodb+srv://Divi_01:Divi123@cluster0.tpjds.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Cluster0

# Security Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.com.chat.chatapp=DEBUG

# Gemini AI Configuration
gemini.api.key=AIzaSyAfY52MhDJbH53mPcXkTq4iy6kbwlPvGWk

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB